# Generated by Django 5.1.2 on 2024-11-25 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0013_alter_comment_author_alter_follow_follower_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
