# Generated by Django 5.1.2 on 2024-12-04 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0017_alter_post_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='subscription',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='followers_count',
        ),
    ]
